name: Post Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - shell: pwsh
        run: ./update-tag.ps1
      - shell: pwsh
        run: az bicep build --file bicep/spot-workers.bicep --outfile bicep/spot-workers.deploymentTemplate.json --verbose
      - name: Commit and push if data has changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date --iso-8601=seconds)
          git commit -m "Updated ARM JSON: ${timestamp}" || exit 0
          git push
